=== ivanadonchevska/XML-Project/XmlToPdf/src/main/resources/football_teams.dtd
<!ELEMENT football (leagues, football_teams, coaches)>

<!ELEMENT leagues (league*)>
    <!ELEMENT league (league_name, league_logo, country, number_of_teams, league_founded)>
        <!ATTLIST league id ID #REQUIRED>
       <!ELEMENT league_name (#PCDATA)>
       <!ELEMENT league_logo EMPTY>
       <!ATTLIST league_logo src ENTITY #REQUIRED>
        <!ELEMENT country (#PCDATA)>
        <!ELEMENT number_of_teams (#PCDATA)>
       <!ELEMENT league_founded (#PCDATA)>

<!ELEMENT football_teams (football_team*)>
    <!ELEMENT football_team (name, logo, founded, stadium, location, captain, description)>
        <!ATTLIST football_team id ID #REQUIRED
                                coachRef IDREF #IMPLIED
                                leagueRef IDREF #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT logo EMPTY>
        <!ATTLIST logo src ENTITY #REQUIRED>
        <!ELEMENT founded (#PCDATA)>
        <!ELEMENT stadium  (#PCDATA)>
        <!ELEMENT location (#PCDATA)>
        <!ELEMENT captain (#PCDATA)>
        <!ELEMENT description (#PCDATA)>

<!ELEMENT coaches (coach*)>
    <!ELEMENT coach (coach_name, photo?, birth_date, coach_since)>
        <!ATTLIST coach id ID #REQUIRED
                        teamRef IDREF #REQUIRED>
       <!ELEMENT coach_name (#PCDATA)>
        <!ELEMENT photo EMPTY>
        <!ATTLIST photo src ENTITY #REQUIRED>
        <!ELEMENT birth_date (#PCDATA)>
        <!ELEMENT coach_since (#PCDATA)>

=== ivanadonchevska/XML-Project/football_teams.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- <?xml-stylesheet type="text/xsl" href="football_teams.xsl"?>  -->
<!DOCTYPE football SYSTEM "football_teams.dtd"[
		<!NOTATION PNG SYSTEM "image/png">
		<!NOTATION JPG SYSTEM "image/jpeg">

		<!ENTITY la_liga SYSTEM "images/La_Liga.png" NDATA PNG>
		<!ENTITY premier_league SYSTEM "images/Premier_League.png" NDATA PNG>
		<!ENTITY serie_a SYSTEM "images/Serie_A.png" NDATA PNG>
		<!ENTITY bundesliga SYSTEM "images/Bundesliga.png" NDATA PNG>
		
		<!ENTITY fc_barcelona SYSTEM "images/Barcelona.png" NDATA PNG>
		<!ENTITY real_madrid SYSTEM "images/Real_Madrid.png" NDATA PNG>
		<!ENTITY bayern SYSTEM "images/Bayern.png" NDATA PNG>
		<!ENTITY dortmund SYSTEM "images/Dortmund.png" NDATA PNG>
		<!ENTITY man_united SYSTEM "images/ManUnited.png" NDATA PNG>
		<!ENTITY man_city SYSTEM "images/ManCity.png" NDATA PNG>
		<!ENTITY juventus SYSTEM "images/Juventus.png" NDATA PNG>
		<!ENTITY milan SYSTEM "images/Milan.png" NDATA PNG>
		<!ENTITY inter SYSTEM "images/Inter.png" NDATA PNG>
        
		<!ENTITY xavi SYSTEM "images/Xavi.jpg" NDATA JPG>
        <!ENTITY ancelotti SYSTEM "images/Ancelotti.jpg" NDATA JPG>
        <!ENTITY nagelsmann SYSTEM "images/Nagelsmann.jpg" NDATA JPG>
        <!ENTITY terzic SYSTEM "images/Terzic.jpg" NDATA JPG>
        <!ENTITY hag SYSTEM "images/Hag.jpg" NDATA JPG>
        <!ENTITY guardiola SYSTEM "images/Guardiola.jpg" NDATA JPG>
		<!ENTITY allegri SYSTEM "images/Allegri.jpg" NDATA JPG> 
		<!ENTITY pioli SYSTEM "images/Pioli.jpg" NDATA JPG> 
		<!ENTITY inzaghi SYSTEM "images/Inzaghi.jpg" NDATA JPG> 
]>

<football>
    <leagues>
        <league id="LL">
            <name>La Liga</name>
            <logo src="la_liga"/>
            <country>Spain</country>
            <number_of_teams>20</number_of_teams>
            <founded>1929</founded>
            <!-- <current_champions></current_champions> -->
        </league>
        
        <league id="PL">
            <name>Premier League</name>
            <logo src="premier_league"/>
            <country>England</country>
            <number_of_teams>20</number_of_teams>
            <founded>1992</founded>
        </league>
    
        <league id="SerieA">
            <name>Serie A</name>
            <logo src="serie_a"/>
            <country>Italy</country>
            <number_of_teams>20</number_of_teams>
            <founded>1929</founded>
        </league>

        <league id="Bundesliga">
            <name>Bundesliga</name>
            <logo src="bundesliga"/>
            <country>Germany</country>
            <number_of_teams>18</number_of_teams>
            <founded>1963</founded>
        </league>
    </leagues>
    
    <football_teams>
        <football_team id="BAR" coachRef="Xavi" leagueRef = "LL">
            <name>FC Barcelona</name>
            <logo src="fc_barcelona"/>
            <founded>1899</founded>
            <stadium>Spotify Camp Nou</stadium>
            <location>Barcelona, Spain</location>
            <captain>Sergio Busquets</captain>
            <description>Futbol Club Barcelona, commonly referred to as Barcelona and colloquially known as Barça, is a professional football club 
                        based in Barcelona, Catalonia, Spain, that competes in La Liga, the top flight of Spanish football.</description>
        </football_team>

        <football_team id="RMA" coachRef="Ancelotti" leagueRef = "LL">
            <name>Real Madrid CF</name>
            <logo src="real_madrid"/>
            <founded>1902</founded>
            <stadium>Santiago Bernabeu</stadium>
            <location>Madrid, Spain</location>
            <captain>Karim Benzema</captain>
            <description>Real Madrid Club de Fútbol meaning Royal Madrid Football Club, 
                        commonly referred to as Real Madrid, is a Spanish professional football club based in Madrid.</description>
        </football_team>

        <football_team id="FCB" coachRef="Nagelsmann" leagueRef = "Bundesliga">
            <name>Fußball-Club Bayern München</name>
            <logo src="bayern"/>
            <founded>1900</founded>
            <stadium>Allianz Arena</stadium>
            <location>Munich, Germany</location>
            <captain>Manuel Neuer</captain>
            <description>Fußball-Club Bayern München, also known as FC Bayern, Bayern Munich, or simply Bayern, is a German professional sports club based in Munich, Bavaria. 
                        It is best known for its professional men's football team, which plays in the Bundesliga, the top tier of the German football league system. 
                        Bayern is the most successful club in German football history, having won a record 32 national titles, 
                        including 10 consecutively since 2013, and 20 national cups, along with numerous European honours.</description>
        </football_team>

        <football_team id="DOR" coachRef="Terzic" leagueRef = "Bundesliga">
            <name>Borussia Dortmund</name>
            <logo src="dortmund"/>
            <founded>1909</founded>
            <stadium>Signal Iduna Park</stadium>
            <location>Dortmund, Germany</location>
            <captain>Jude Bellingham</captain>
            <description>Ballspielverein Borussia 09 e. V. Dortmund, commonly known as Borussia Dortmund, BVB or simply Dortmund, 
                        is a German professional sports club based in Dortmund, North Rhine-Westphalia. 
                        It is best known for its men's professional football team, which plays in the Bundesliga, the top tier of the German football league system. 
                        The club have won eight league championships, five DFB-Pokals,
                        one UEFA Champions League, one Intercontinental Cup, and one UEFA Cup Winners' Cup.</description>
        </football_team>


        <football_team id="MNU" coachRef="Hag" leagueRef = "PL">
            <name>Manchester United</name>
            <logo src="man_united"/>
            <founded>1878</founded>
            <stadium>Old Trafford</stadium>
            <location>Manchester, England</location>
            <captain>Harry Maguire</captain>
            <description>Manchester United Football Club, commonly referred to as Man United (often stylised as Man Utd), or simply United, 
                        is a professional football club based in Old Trafford, Greater Manchester, England. The club competes in the Premier League, 
                        the top division in the English football league system. Nicknamed the Red Devils, it was founded as Newton Heath LYR Football Club in 1878, 
                        but changed its name to Manchester United in 1902. The club moved from Newton Heath to its current stadium, Old Trafford, in 1910.</description>
        </football_team>

        
        <football_team id="MNC" coachRef="Guardiola" leagueRef = "PL">
            <name>Manchester City</name>
            <logo src="man_city"/>
            <founded>1880</founded>
            <stadium>City of Manchester Stadium</stadium>
            <location>Manchester, England</location>
            <captain>Ilkay Gundogan</captain>
            <description>Manchester City Football Club are an English football club based in Manchester that competes in the Premier League, 
                        the top flight of English football. Founded in 1880 as St. Mark's (West Gorton), 
                        they became Ardwick Association Football Club in 1887 and Manchester City in 1894.
                        The club's home ground is the Etihad Stadium in east Manchester, to which they moved in 2003, having played at Maine Road since 1923. 
                        Manchester City adopted their sky blue home shirts in 1894, in the first season with the current name.[3] Over the course of its history, 
                        the club has won eight league titles, six FA Cups, eight League Cups, six FA Community Shields, and one European Cup Winners' Cup, 
                        making them the fifth most successful club in English football.</description>
        </football_team>

        <football_team id="JUV" coachRef="Allegri" leagueRef = "SerieA">
            <name>Juventus</name>
            <logo src="juventus"/>
            <founded>1897</founded>
            <stadium>Juventus Stadium</stadium>
            <location>Turin, Italy</location>
            <captain>Leonardo Bonucci</captain>
            <description>Juventus Football Club (from Latin: iuventūs, 'youth'), colloquially known as Juve is a professional football club based in Turin, Piedmont, Italy,
                        that competes in the Serie A, the top tier of the Italian football league system. Founded in 1897 by a group of Torinese students, 
                        the club has worn a black and white striped home kit since 1903 and has played home matches in different grounds around its city, 
                        the latest being the 41,507-capacity Juventus Stadium. Nicknamed Vecchia Signora ("the Old Lady"), the club has won 36 official league titles,
                        14 Coppa Italia titles and nine Supercoppa Italiana titles, being the record holder for all these competitions; two Intercontinental Cups,
                        two European Cups / UEFA Champions Leagues, one European Cup Winners' Cup, a joint national record of three UEFA Cups,
                        two UEFA Super Cups and a joint national record of one UEFA Intertoto Cup.[6][7] Consequently, the side leads the historical Federazione
                        Italiana Giuoco Calcio (FIGC) classification[c] whilst on the international stage occupies the sixth position in Europe and the twelfth in
                        the world for most confederation titles won with eleven trophies,[9] as well as the fourth in the all-time
